# Generated by Django 4.2 on 2023-05-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_discount_untill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_untill',
            new_name='discount_until',
        ),
    ]
