# Generated by Django 4.2 on 2023-05-27 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(blank=True, max_length=60, null=True)),
                ('Telefono', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('FechaInclusion', models.DateField(default=datetime.date.today)),
                ('Notas', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
